# Copyright (c) 2026, AgriTheory and contributors
# For license information, please see license.txt

employees = [
	{
		"company": "Chelsea Fruit Co",
		"date_of_birth": "1977-03-06",
		"date_of_joining": "2019-04-12",
		"employee_name": "Arden Rivers",
		"employment_type": "Full-time",
		"first_name": "Arden",
		"gender": "Male",
		"last_name": "Rivers",
		"status": "Active",
		"tin": "004-48-0067",
		"roles": ["Stock Manager", "Item Manager"],
		"designation": "Warehouse Manager",
		"reports_to": "Darnell Benton",
	},
	{
		"company": "Chelsea Fruit Co",
		"date_of_birth": "1984-04-23",
		"date_of_joining": "2019-07-04",
		"employee_name": "Minh McKay",
		"employment_type": "Full-time",
		"first_name": "Minh",
		"gender": "Female",
		"last_name": "McKay",
		"status": "Active",
		"tin": "002-27-6877",
		"roles": ["Sales User", "Sales Manager", "Sales Master Manager"],
		"designation": "Head of Marketing and Sales",
		"reports_to": "Darnell Benton",
	},
	{
		"company": "Chelsea Fruit Co",
		"date_of_birth": "1980-07-06",
		"date_of_joining": "2019-07-28",
		"employee_name": "Morgan Britt",
		"employment_type": "Full-time",
		"first_name": "Morgan",
		"gender": "Female",
		"last_name": "Britt",
		"status": "Active",
		"tin": "009-00-2414",
		"roles": [
			"Accounts Manager",
			"Accounts User",
			"Purchase User",
			"Purchase Manager",
			"Purchase Master Manager",
		],
		"designation": "Chief Financial Officer",
		"reports_to": "Darnell Benton",
	},
	{
		"company": "Chelsea Fruit Co",
		"date_of_birth": "1984-06-29",
		"date_of_joining": "2020-01-12",
		"employee_name": "Marcellus Reeves",
		"employment_type": "Full-time",
		"first_name": "Marcellus",
		"gender": "Male",
		"last_name": "Reeves",
		"status": "Active",
		"tin": "003-47-4528",
		"roles": ["Stock User"],
		"designation": "Associate",
		"reports_to": "Arden Rivers",
	},
	{
		"company": "Chelsea Fruit Co",
		"date_of_birth": "1998-04-22",
		"date_of_joining": "2020-03-20",
		"designation": "Associate",
		"employee_name": "Assunta Jimenez",
		"employment_type": "Full-time",
		"first_name": "Assunta",
		"gender": "Female",
		"last_name": "Jimenez",
		"status": "Active",
		"tin": "002-90-1544",
		"roles": ["Stock User"],
		"reports_to": "Arden Rivers",
	},
	{
		"company": "Chelsea Fruit Co",
		"date_of_birth": "1979-06-18",
		"date_of_joining": "2020-09-08",
		"designation": "Associate",
		"employee_name": "Alton Sears",
		"employment_type": "Full-time",
		"first_name": "Alton",
		"gender": "Male",
		"last_name": "Sears",
		"status": "Active",
		"tin": "000-52-4669",
		"roles": ["Stock User"],
		"reports_to": "Arden Rivers",
	},
	{
		"company": "Chelsea Fruit Co",
		"date_of_birth": "1991-08-17",
		"date_of_joining": "2020-11-01",
		"designation": "Associate",
		"employee_name": "Eli Serrano",
		"employment_type": "Full-time",
		"first_name": "Eli",
		"gender": "Male",
		"last_name": "Serrano",
		"status": "Active",
		"tin": "000-49-0783",
		"roles": ["Stock User"],
		"reports_to": "Arden Rivers",
	},
	{
		"company": "Chelsea Fruit Co",
		"date_of_birth": "1997-09-13",
		"date_of_joining": "2021-02-22",
		"employee_name": "Sumiko Kim",
		"employment_type": "Full-time",
		"first_name": "Sumiko",
		"gender": "Female",
		"last_name": "Kim",
		"status": "Active",
		"tin": "004-82-6553",
		"roles": ["Sales User"],
		"designation": "Sales Representative",
		"reports_to": "Minh McKay",
	},
	{
		"company": "Chelsea Fruit Co",
		"date_of_birth": "1979-11-08",
		"date_of_joining": "2021-03-11",
		"employee_name": "Riley Sutton",
		"employment_type": "Full-time",
		"first_name": "Riley",
		"gender": "Other",
		"last_name": "Sutton",
		"status": "Active",
		"tin": "002-23-2941",
		"roles": ["Sales User"],
		"designation": "Sales Representative",
		"reports_to": "Minh McKay",
	},
	{
		"company": "Chelsea Fruit Co",
		"date_of_birth": "1987-07-10",
		"date_of_joining": "2021-06-21",
		"employee_name": "Andrea Buchanan",
		"employment_type": "Full-time",
		"first_name": "Andrea",
		"gender": "Female",
		"last_name": "Buchanan",
		"status": "Active",
		"tin": "007-91-4605",
		"roles": ["Stock User"],
		"designation": "Associate",
		"reports_to": "Arden Rivers",
	},
	{
		"company": "Chelsea Fruit Co",
		"date_of_birth": "1994-07-27",
		"date_of_joining": "2021-06-24",
		"employee_name": "Rashad Bruce",
		"employment_type": "Full-time",
		"first_name": "Rashad",
		"gender": "Male",
		"last_name": "Bruce",
		"status": "Active",
		"tin": "004-84-1349",
		"roles": ["Sales User"],
		"designation": "Sales Representative",
		"reports_to": "Minh McKay",
	},
	{
		"company": "Chelsea Fruit Co",
		"date_of_birth": "1999-10-04",
		"date_of_joining": "2021-08-01",
		"employee_name": "Darnell Benton",
		"employment_type": "Full-time",
		"first_name": "Darnell",
		"gender": "Female",
		"last_name": "Benton",
		"status": "Active",
		"tin": "006-77-6510",
		"designation": "Chief Executive Officer",
		"roles": [
			"Item Manager",
			"Sales User",
			"Sales Manager",
			"Sales Master Manager",
			"Accounts Manager",
			"Accounts User",
			"HR Manager",
			"HR User",
			"Stock User",
			"Sales User",
		],
	},
]

holidays = [
	{
		"from_date": "2024-01-01",
		"holiday_list_name": "2024 - United States",
		"country": "United States",
		"holidays": [
			{"description": "New Year's Day", "holiday_date": "2024-01-01"},
			{"description": "Birthday of Martin Luther King, Jr.", "holiday_date": "2024-01-15"},
			{"description": "Washington's Birthday", "holiday_date": "2024-02-19"},
			{"description": "Memorial Day", "holiday_date": "2024-05-27"},
			{"description": "Juneteenth National Independence Day", "holiday_date": "2024-06-19"},
			{"description": "Independence Day", "holiday_date": "2024-07-04"},
			{"description": "Labor Day", "holiday_date": "2024-09-02"},
			{"description": "Columbus Day", "holiday_date": "2024-10-14"},
			{"description": "Veterans Day", "holiday_date": "2024-11-11"},
			{"description": "Thanksgiving Day", "holiday_date": "2024-11-28"},
			{"description": "Christmas Day", "holiday_date": "2024-12-25"},
		],
		"to_date": "2024-12-31",
	},
	{
		"from_date": "2025-01-01",
		"holiday_list_name": "2025 - United States",
		"country": "United States",
		"holidays": [
			{"description": "New Year's Day", "holiday_date": "2025-01-01"},
			{"description": "Birthday of Martin Luther King, Jr.", "holiday_date": "2025-01-20"},
			{"description": "Washington's Birthday", "holiday_date": "2025-02-17"},
			{"description": "Memorial Day", "holiday_date": "2025-05-26"},
			{"description": "Juneteenth National Independence Day", "holiday_date": "2025-06-19"},
			{"description": "Independence Day", "holiday_date": "2025-07-04"},
			{"description": "Labor Day", "holiday_date": "2025-09-01"},
			{"description": "Columbus Day", "holiday_date": "2025-10-13"},
			{"description": "Veterans Day", "holiday_date": "2025-11-11"},
			{"description": "Thanksgiving Day", "holiday_date": "2025-11-27"},
			{"description": "Christmas Day", "holiday_date": "2025-12-25"},
		],
		"to_date": "2025-12-31",
	},
]
